pub(super) use crate::Result;
pub(super) use reqwest::Method;
pub(super) use serde_json::{json, Value};

pub(super) use super::client::OpenApiClient;
pub(super) use super::config::OpenApiPaths;
pub(super) use super::token::TokenProvider;
pub(super) use super::utils::{append_query, render_path, require_path};

mod announces;
mod api_permissions;
mod c2c_messages;
mod channel_permissions;
mod channels;
mod forums;
mod guilds;
mod interactions;
mod members;
mod message_settings;
mod mute;
mod open_api;
mod pins;
mod reactions;
mod roles;
mod schedules;
mod users;

pub use announces::AnnouncesApi;
pub use api_permissions::ApiPermissionsApi;
pub use c2c_messages::C2cMessagesApi;
pub use channel_permissions::ChannelPermissionsApi;
pub use channels::ChannelsApi;
pub use forums::ForumsApi;
pub use guilds::GuildsApi;
pub use interactions::InteractionsApi;
pub use members::MembersApi;
pub use message_settings::MessageSettingsApi;
pub use mute::MuteApi;
pub use open_api::OpenApi;
pub use pins::PinsApi;
pub use reactions::ReactionsApi;
pub use roles::RolesApi;
pub use schedules::SchedulesApi;
pub use users::UsersApi;
